# Generated by Django 4.2.7 on 2023-11-14 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='bio',
            new_name='Investment_objectives',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='website',
        ),
        migrations.AddField(
            model_name='setting',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='setting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
