# Generated by Django 4.2.7 on 2023-11-14 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_bio_setting_investment_objectives_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='email',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='setting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
