# Generated by Django 4.2.7 on 2023-11-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_setting_email_remove_setting_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='Profile',
        ),
    ]
