# Generated by Django 4.2.7 on 2023-11-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_setting_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='investment_objectives',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
