# Generated by Django 4.2.7 on 2023-11-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_investment_objectives_user_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='amount_to_invest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='fund_type',
            field=models.CharField(choices=[('CI', 'Citadel Fund'), ('CA', 'Capernaum Fund'), ('SM', 'Selby Medallion Fund')], default='CI', max_length=15),
        ),
    ]
