# Generated by Django 4.2.7 on 2023-11-16 08:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_login_delete_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Investment_objectives',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='investment_objectives',
            field=models.CharField(default='', max_length=750),
        ),
    ]
