# Generated by Django 4.2.7 on 2023-11-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_profile_investment_objectives_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount_to_invest',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='fund_type',
            field=models.CharField(blank=True, choices=[('CI', 'Citadel Fund'), ('CA', 'Capernaum Fund'), ('SM', 'Selby Medallion Fund')], default='CI', max_length=15),
        ),
    ]
