# Generated by Django 4.2.7 on 2023-11-23 07:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_amount_to_invest_alter_user_fund_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount_to_invest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='fund_type',
            field=models.CharField(choices=[('CI', 'Citadel Fund'), ('CA', 'Capernaum Fund'), ('SM', 'Selby Medallion Fund')], default='CI', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
