# Generated by Django 4.2.7 on 2023-11-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='investment_objectives',
            field=models.CharField(default='None', max_length=750),
        ),
    ]
